"""Application Use Cases"""

from .base import (
    AlreadyExistsError,
    NotFoundError,
    UseCase,
    UseCaseError,
    ValidationError,
)
from .simulation_use_cases import (
    AnalyzeFieldRequest,
    AnalyzeFieldResponse,
    AnalyzeFieldUseCase,
    CompareTimestepsRequest,
    CompareTimestepsResponse,
    CompareTimestepsUseCase,
    ComputeConvergenceRequest,
    ComputeConvergenceResponse,
    ComputeConvergenceUseCase,
    GetSimulationRequest,
    GetSimulationResponse,
    GetSimulationUseCase,
    ListSimulationsRequest,
    ListSimulationsResponse,
    ListSimulationsUseCase,
    SimulationSummary,
    SpatialAnalysisRequest,
    SpatialAnalysisResponse,
    SpatialAnalysisUseCase,
    UploadSimulationRequest,
    UploadSimulationResponse,
    UploadSimulationUseCase,
)

__all__ = [
    # Base
    "UseCase",
    "UseCaseError",
    "ValidationError",
    "NotFoundError",
    "AlreadyExistsError",
    # Simulation Use Cases
    "UploadSimulationUseCase",
    "UploadSimulationRequest",
    "UploadSimulationResponse",
    "GetSimulationUseCase",
    "GetSimulationRequest",
    "GetSimulationResponse",
    "AnalyzeFieldUseCase",
    "AnalyzeFieldRequest",
    "AnalyzeFieldResponse",
    "CompareTimestepsUseCase",
    "CompareTimestepsRequest",
    "CompareTimestepsResponse",
    "ComputeConvergenceUseCase",
    "ComputeConvergenceRequest",
    "ComputeConvergenceResponse",
    "SpatialAnalysisUseCase",
    "SpatialAnalysisRequest",
    "SpatialAnalysisResponse",
    "ListSimulationsUseCase",
    "ListSimulationsRequest",
    "ListSimulationsResponse",
    "SimulationSummary",
]
